---
- name: Install and Configure MySQL
  hosts: mySQL
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - python3-pip
        - python3-pymysql

    - name: Start MySQL service
      service:
        name: mysql
        state: started

    - name: Secure MySQL installation
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: EmersonFitipaldi
        user: ivansto
        password: EmersonFitipaldi
        host: "%"
        priv: "*.*:ALL,GRANT"
        state: present

    - name: Update MySQL server configuration file
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'
      notify: Restart MySQL Service

  handlers:
    - name: Restart MySQL Service
      service:
        name: mysql
        state: restarted

- name: Create 'words' Database Task
  hosts: mySQL
  become: true
  tasks:
    - name: Ensure 'words' database exists
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        login_password: EmersonFitipaldi
        name: words
        state: present

